\c cart_dev;

INSERT INTO store (store_name, store_address, store_city, store_state, store_zipCode, store_image, store_hours, store_accepts_EBT, store_phone_number)
VALUES
    ('City Fresh Market', '229 Knickerbocker Ave #2401', 'Brooklyn', 'NY', 11237, 'https://www.cityfreshmarket.com/wp_2013/wp-content/uploads/2021/08/City-Fresh-Market_store-exterior.jpg', 'Mon - Sat 24 hours', true, '(123) 456-7890'),
    ('Mr. Lemon', '410 Knickerbocker Ave', 'Brooklyn', 'NY', 11237, 'https://db535g4onu9gg.cloudfront.net/eyJidWNrZXQiOiJtZXJjYXRvLWltYWdlcyIsImVkaXRzIjp7InJlc2l6ZSI6eyJmaXQiOiJmaWxsIiwid2lkdGgiOjM5MCwiaGVpZ2h0IjozOTB9fSwia2V5Ijoic3RvcmUtaW1hZ2VzLzRhSnlQaVFGT0RaQTJEa0ZjeTB0R1plemVyaGpzaWF0VGp0eW0yckQuanBnIn0=', '7:00 AM - 11:00 PM', false, '(987) 654-3210'),
    ('bp', '1379 Halsey St', 'Brooklyn', 'NY', 11237, 'https://bloximages.chicago2.vip.townnews.com/moraminn.com/content/tncms/assets/v3/editorial/c/4b/c4bf0a28-c630-11ec-9790-63a59f47cc38/62694a51438ea.image.jpg?resize=400%2C200', 'Mon-Fri: 8am-10pm, Sat-Sun: 9am-9pm', true, '(789) 012-3456'),
    ('Buena Vista Deli & Grocery', '152 Knickerbocker Ave', 'Brooklyn', 'NY', 11237, 'https://media-cdn.tripadvisor.com/media/photo-s/17/6a/4f/10/buena-vista-market.jpg', '9:00 AM - 9:00 PM', true, '(555) 123-4567'),
    ('EUROPE', '307 Brighton Beach Ave', 'Brooklyn', 'NY', 11235, 'https://l450v.alamy.com/450v/2hg6c26/brighton-beach-brooklyn-new-york-city-new-york-usa-november-6-2021-market-selling-european-foods-in-brooklyn-2hg6c26.jpg', '8:00 AM - 8:00 PM', true, '(222) 999-7777'),
    ('Atlantis', '1127 Flushing Ave', 'Brooklyn', 'NY', 11237, 'https://s3-media0.fl.yelpcdn.com/bphoto/FtRIzIYwZm9ELWJjd-ZcYA/348s.jpg', '10:00 AM - 8:00 PM', true, '(246) 135-7900'),
    ('Valery Deli Grocery Store', '214 Knickerbocker Ave', 'Brooklyn', 'NY', 11237, 'https://lh3.googleusercontent.com/p/AF1QipNveMLhM6XARij34NCdDN1hz2OOE9EiCmu3ERVa=w1080-h608-p-no-v0', '7:30 AM - 9:30 PM', true, '(888) 555-1212'),
    ('Clasico Grocery', '343 Knickerbocker Ave', 'Brooklyn', 'NY', 11237, 'https://fastly.4sqi.net/img/general/600x600/52267008_Ysly7MFq4edyrFJKhMH3-q_KjqPkKW0UR9WXdlEKTRk.jpg', '9:00 AM - 7:00 PM', true, '(444) 777-3333'),
    ('To The World Farm', '655 Grand St #4854', 'Brooklyn', 'NY', 11211, 'https://ir.4sqi.net/img/general/original/XQ55DNA0OJ25DMNN40BPAECWKQSZ10LZSJK1FCRUZBCB1QSP.jpg', '10:30 AM - 6:30 PM', false, '(777) 111-3333'),
    ('Williams Avenue Community Garden', '88 Williams Ave', 'Brooklyn', 'NY', 11207, 'https://williams.mapseed.org/static/css/images/Willams-Ave-BK.jpg', '6:00 AM - 12:00 AM', false, '(321) 654-9870');

INSERT INTO product (store_id, product_name, product_image, product_description, product_category, product_weight, product_price, product_discount, product_unit, product_brand, product_is_tree_nuts_free, product_is_egg_free, product_is_fresh, product_is_frozen, product_is_halal, product_is_kosher, product_is_non_processed, product_is_organic, product_is_vegetarian, product_is_stock, product_is_vegan_friendly, product_is_seafood, product_is_peanut_free
product_is_caffeine,product_is_dairy_free product_is_no_preservatives, product_is_no_added_sugar, product_is_nuts_free, product_is_keto_friendly, product_is_low_carb_diet, product_is_gluten_free, product_is_international)
VALUES
    (1, 'Apples', 'https://thumbs.dreamstime.com/b/red-apple-isolated-white-background-45573196.jpg', 'Fresh, juicy apples', 'Fruits', 0.5, 1.99, 0, 'lb', 'NatureFresh', 'None', 'None', 'None', true, false, false, false, true, true, true, true, false, false),
    (2, 'Bananas', 'https://img.freepik.com/premium-photo/bunch-bananas-isolated-white-background-ripe-bananas-clipping-path-quality-macro-photo-your-project_517510-2967.jpg?w=2000', 'Sweet, ripe bananas', 'Fruits', 0.3, 0.49, 0, 'lb', 'Tropical Delights', 'None', 'None', 'None', true, false, false, false, true, true, true, true, false, false),
    (3, 'Crispy Chips', 'https://media.istockphoto.com/id/458678045/photo/lays-potato-chips.jpg?s=612x612&w=0&k=20&c=vm2Gy6O7wr7PTIkdIntIiBZVUJiisHwyxcK6hYbrNT8=', 'Delicious potato chips', 'Snacks', 0.2, 2.99, 0, 'bag', 'Tasty Treats', 'None', 'None', 'None', false, false, true, false, true, false, false, true, true, false),
    (4, 'Oranges', 'https://media.istockphoto.com/id/182463420/photo/tangerine-duo-with-leafs.jpg?s=612x612&w=0&k=20&c=d3JZRAqgqZ5RWyN4ryFteCnmFNbeD9e3TNJkS2IC0vU=', 'Fresh, tangy oranges', 'Fruits', 0.4, 0.79, 0, 'lb', 'NatureFresh', 'None', 'None', 'None', true, false, false, false, true, true, true, true, false, false),
    (6, 'Grapes', 'https://img.freepik.com/premium-photo/grapes-white-background_181303-4423.jpg', 'Juicy red grapes', 'Fruits', 0.6, 2.49, 0, 'lb', 'Vineyard Delights', 'None', 'None', 'None', true, false, false, false, true, true, true, true, false, false),
    (3, 'Potato Chips', 'https://www.seekpng.com/png/detail/761-7619514_doritos-nacho-cheese-doritos-bag-transparent-background.png', 'Classic potato chips', 'Snacks', 0.15, 1.49, 0, 'bag', 'SnackWorld', 'None', 'None', 'None', false, false, true, false, true, false, false, true, true, false),
    (2, 'Strawberries', 'https://d2gg9evh47fn9z.cloudfront.net/1600px_COLOURBOX3444441.jpg', 'Fresh, sweet strawberries', 'Fruits', 0.3, 3.99, 0, 'lb', 'Berry Bliss', 'None', 'None', 'None', true, false, false, false, true, true, true, true, false, false),
    (5, 'Milk', 'https://www.pngitem.com/pimgs/m/111-1112579_milk-gallon-png-milk-carton-transparent-background-png.png', 'Fresh whole milk', 'Dairy', 1, 2.29, 0, 'gallon', 'DairyDelight', 'None', 'None', 'None', true, true, false, false, true, true, false, true, false, false),
    (1, 'Cereal', 'https://target.scene7.com/is/image/Target/GUEST_9b329235-1ff4-4ab2-af07-99f8828df528?wid=488&hei=488&fmt=pjpeg', 'Nutty cereal flakes', 'Breakfast', 0.8, 3.99, 0, 'box', 'BreakfastBites', 'None', 'None', 'None', false, false, true, false, true, true, true, true, false, false),
    (9, 'Bread', 'https://thumbs.dreamstime.com/b/lot-different-bread-white-background-isolated-95772001.jpg', 'Fresh whole wheat bread', 'Bakery', 1, 2.99, 0, 'loaf', 'BakeryBest', 'None', 'None', 'None', true, false, true, true, true, true, true, true, false, false),
    (10, 'Carrots', 'https://t4.ftcdn.net/jpg/00/80/96/17/360_F_80961739_hep1UZaQRsy5WQOYU3jkOr5CB7A6xc3U.jpg', 'Crunchy, fresh carrots', 'Vegetables', 0.4, 0.89, 0, 'lb', 'Harvest Farms', 'None', 'None', 'None', true, false, false, false, true, true, true, true, false, false),
    (7, 'Eggs', 'https://media.istockphoto.com/id/467061077/photo/eggs-isolated-on-a-white-background.jpg?s=612x612&w=0&k=20&c=K6RZK8UR5hzHy4auNEKHV0EdkBVnVlyLlfBflpUXP-g=', 'Farm-fresh eggs', 'Dairy', 0.75, 1.99, 0, 'dozen', 'FarmFresheggs', 'None', 'None', 'None', true, true, false, false, true, true, false, true, false, false),
    (8, 'Juice', 'https://media.istockphoto.com/id/171114622/photo/glass-of-orange-juice-and-three-oranges-over-white-backdrop.jpg?s=612x612&w=0&k=20&c=R9tzhhF-wYAYm7FoVzabI1iCs9_jMopXM38j6P9HhP8=', 'Refreshing fruit juice', 'Beverages', 1, 3.49, 0, 'bottle', 'JuiceFusion', 'None', 'None', 'None', true, false, false, false, true, true, true, true, false, false),
    (2, 'Oranges', 'https://media.istockphoto.com/id/182463420/photo/tangerine-duo-with-leafs.jpg?s=612x612&w=0&k=20&c=d3JZRAqgqZ5RWyN4ryFteCnmFNbeD9e3TNJkS2IC0vU=', 'Fresh, tangy oranges', 'Fruits', 0.4, 0.79, 0, 'lb', 'NatureFresh', 'None', 'None', 'None', true, false, false, false, true, true, true, true, false, false),
    (5, 'Tuna', 'https://media.istockphoto.com/id/466869031/photo/bumble-bee-tuna-can.jpg?s=612x612&w=0&k=20&c=I8YJhBEdVOJuYQ1xsBCydubTt42gDEnTxoYTwG0bPHc=', 'Wild-caught tuna fillet', 'Seafood', 0.3, 6.99, 0, 'lb', 'OceanCatch', 'None', 'None', 'None', false, true, true, false, true, true, false, true, false, true),
    (3, 'Potato Chips', 'https://meaningfuleats.com/wp-content/uploads/2023/03/takis-gluten-free.jpg', 'Classic potato chips', 'Snacks', 0.15, 1.49, 0, 'bag', 'SnackWorld', 'Contains soy', 'None', 'None', false, false, true, false, true, false, false, true, true, false),
    (1, 'Strawberries', 'https://d2gg9evh47fn9z.cloudfront.net/1600px_COLOURBOX3444441.jpg', 'Fresh, sweet strawberries', 'Fruits', 0.3, 3.99, 0, 'lb', 'Berry Bliss', 'None', 'None', 'None', true, false, false, false, true, true, true, true, false, false),
    (4, 'Salmon', 'https://media.istockphoto.com/id/1176250147/photo/raw-salmon-piece-isolated-on-white-background.jpg?s=612x612&w=0&k=20&c=UhFaL4j7Lmabiti4WEN3xsBVvzRdcwMt0R6bimPROUk=', 'Wild-caught salmon fillet', 'Seafood', 0.5, 9.99, 0, 'lb', 'SeaHarvest', 'None', 'None', 'None', false, true, true, false, true, true, false, true, false, true),
    (6, 'Carrots', 'https://t4.ftcdn.net/jpg/00/80/96/17/360_F_80961739_hep1UZaQRsy5WQOYU3jkOr5CB7A6xc3U.jpg', 'Crunchy, fresh carrots', 'Vegetables', 0.4, 0.89, 0, 'lb', 'Harvest Farms', 'None', 'None', 'None', true, false, false, false, true, true, true, true, false, false),
    (2, 'Apples', 'https://static.vecteezy.com/system/resources/previews/002/078/428/large_2x/green-apple-on-white-background-free-photo.jpg', 'Fresh, juicy apples', 'Fruits', 0.5, 1.99, 0, 'lb', 'NatureFresh', 'None', 'None', 'None', true, false, false, false, true, true, true, true, false, false),
    (3, 'Shrimp', 'https://target.scene7.com/is/image/Target/GUEST_f56f9150-5f58-48e2-bfc9-f6b6a2bc126a?wid=488&hei=488&fmt=pjpeg', 'Wild-caught shrimp', 'Seafood', 0.2, 12.99, 0, 'lb', 'SeaTreasures', 'None', 'None', 'None', false, true, true, false, true, true, false, true, false, true),
    (5, 'Almonds', 'https://live.staticflickr.com/65535/48177230762_2ba98c0a55_b.jpg', 'Crunchy roasted almonds', 'Nuts', 0.25, 4.49, 0, 'lb', 'NuttyBites', 'None', 'None', 'None', true, false, false, false, true, true, true, true, false, false),
    (4, 'Pasta', 'https://thumbs.dreamstime.com/b/chisinau-moldova-marth-front-view-barilla-spaghetti-n-italian-pasta-white-background-company-was-founded-as-bakery-shop-112696602.jpg', 'Classic pasta noodles', 'Pasta', 1, 1.29, 0, 'box', 'CarbCraze', 'Contains wheat', 'None', 'None', false, false, true, true, true, true, true, true, false, false),
    (1, 'Kiwi', 'https://img.freepik.com/premium-photo/kiwi-fruit-isolated-white-background_42033-482.jpg?w=2000', 'Fresh, tangy kiwi', 'Fruits', 0.2, 0.89, 0, 'each', 'Tropical Delights', 'None', 'None', 'None', true, false, false, false, true, true, true, true, false, false),
    (6, 'Lobster', 'https://img.freepik.com/premium-photo/red-lobster-isolated-white-background-full-depth-field_88281-5805.jpg?w=2000', 'Fresh lobster tail', 'Seafood', 0.3, 19.99, 0, 'lb', 'SeaLuxury', 'None', 'None', 'None', false, true, true, false, true, true, false, true, false, true),
    (2, 'Yogurt', 'https://media.istockphoto.com/id/840644316/photo/yogurt-with-raspberries-and-blueberries-over-white.jpg?s=612x612&w=0&k=20&c=pmlLz6RDiv4Hemyq-dRJXR7qeExEE3IdQxAZCtX5Ogk=', 'Creamy yogurt', 'Dairy', 0.5, 2.49, 0, 'cup', 'DairyDelight', 'None', 'None', 'None', true, true, false, false,false, false, true, true, true, false),
    (1, 'Eggo Homestyle Waffles', 'https://images.heb.com/is/image/HEBGrocery/000118654-1', 'Crispy, golden, and fluffy ready-to-heat waffles', 'Breakfast & Cereal', 12.3, 'Box', 4.49, 10, 'Eggo', False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False)
    (1, 'Thomas Original Bagels', 'https://www.meijer.com/content/dam/meijer/product/0004/81/2127/70/0004812127707_2_A1C1_1200.png', 'Pre-sliced, classic and soft bagels, perfect for a variety of toppings', 'Breakfast & Cereal', 20, 'Bag', 4.99, 5, 'Thomas', False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False)
    (1, 'Jimmy Dean Original Breakfast Sausage', 'https://target.scene7.com/is/image/Target/GUEST_61b39796-0c9e-4bdc-9730-7a22c06872a6?wid=1200&hei=1200&qlt=80&fmt=webp', 'Classic pork sausage patties with a blend of savory seasonings', 'Breakfast & Cereal', 16, 'Pack', 3.99, 0, 'Jimmy Dean', False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False)
    (1, 'Thomas Original English Muffins', 'https://images.albertsons-media.com/is/image/ABS/196100807-ECOM?$ng-ecom-pdp-desktop$&defaultImage=Not_Available', 'Classic soft and chewy English muffins with Nooks & Crannies for a perfect crisp', 'Breakfast & Cereal', 12, 'Pack', 3.29, 0, 'Thomas', False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False)
    (1, 'Kelloggs Frosted Flakes', 'https://ferebe.com/cdn/shop/products/051bbae1-3ff3-458a-b461-71a71d332480.804403b4d1be9cf2cf1fd4709e455c7b_900x.jpg?v=1623102599', 'Sweetened flaky cereal with a crisp texture, enriched with vitamins and minerals', 'Breakfast & Cereal', 13.5, 'Box', 3.69, 0, 'Kelloggs', False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False),
    (1, 'General Mills Cheerios', 'https://i5.walmartimages.com/seo/Original-Cheerios-Heart-Healthy-Cereal-18-OZ-Family-Size-Cereal-Box_2b78c38c-3a0c-486a-b4bb-96025b072a13.e49a64099b22a26a02ed55a655afe4ca.jpeg?odnHeight=2000&odnWidth=2000&odnBg=FFFFFF', 'Classic whole-grain oats cereal, low in sugar and high in fiber', 'Breakfast & Cereal', 18.0, 'Box', 3.99, 0, 'General Mills', False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False),
    (1, 'Quaker Oats Old Fashioned Oatmeal', 'https://cdnimg.webstaurantstore.com/images/products/large/447564/1651420.jpg', 'Whole grain rolled oats that provide a wholesome start to your day', 'Breakfast & Cereal', 42.0, 'Canister', 5.29, 10, 'Quaker Oats', False, False, True, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False),
    (1, 'Quaker Instant Oatmeal, Variety Pack', 'https://i5.walmartimages.com/asr/e732f663-bda9-49e6-bec9-261dadc46e4b_1.8bda65ecaeba58d944e4ee271b5160a7.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF', 'Flavored instant oatmeal packets with a variety of delicious flavors', 'Breakfast & Cereal', 15.1, 'Box', 3.99, 0, 'Quaker', False, False, True, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False),
    (1, 'Nature Valley Oats n Honey Granola', 'https://m.media-amazon.com/images/I/818Sc5vkDVL.jpg', 'Crunchy granola made with whole grain oats and a touch of honey', 'Breakfast & Cereal', 11.0, 'Pouch', 4.49, 0, 'Nature Valley', False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False),
    (1, 'Belvita Breakfast Biscuits, Blueberry', 'https://target.scene7.com/is/image/Target/GUEST_7d09e1d1-9519-4307-8882-bd35d8c24c7a?wid=1200&hei=1200&qlt=80&fmt=webp', 'Crunchy blueberry flavored breakfast biscuits made with whole grains', 'Breakfast & Cereal', 8.8, 'Box', 3.69, 0, 'Belvita', False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False),
    (1, 'Kelloggs Pop-Tarts, Strawberry', 'https://target.scene7.com/is/image/Target/GUEST_f22db326-9521-455c-850a-aea983087fbb?wid=1200&hei=1200&qlt=80&fmt=webp', 'Toaster pastries with a strawberry filling, topped with a sweet frosting', 'Breakfast & Cereal', 13.5, 'Box', 3.29, 0, 'Kelloggs', False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False),
    (1, 'Pearl Milling Company Original Syrup', 'https://target.scene7.com/is/image/Target/GUEST_7915fbb6-575a-48ed-8388-d0c2a4b472bf?wid=1200&hei=1200&qlt=80&fmt=webp', 'Rich and thick syrup with a classic sweet flavor, ideal for pancakes and waffles', 'Breakfast & Cereal', 24.0, 'Bottle', 3.49, 0, 'Pearl Milling Company', True, True, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False),
    (1, 'Large White Eggs', 'https://images.heb.com/is/image/HEBGrocery/000325137-2', 'Farm-fresh large white eggs', 'Dairy', '12 eggs', 'Dozen', 2.49, 0, 'Generic', False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False),
    (1, 'Large Brown Eggs', 'https://images.heb.com/is/image/HEBGrocery/000313771-3?jpegSize=150&hei=1400&fit=constrain&qlt=75', 'Farm-fresh large brown eggs', 'Dairy', '12 eggs', 'Dozen', 2.79, 5, 'Generic', False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False),
    (1, 'Horizon Organic Whole Milk', 'https://target.scene7.com/is/image/Target/GUEST_2a359408-3f61-45df-95b1-0859e68867c3?wid=1200&hei=1200&qlt=80&fmt=webp', 'Rich and creamy organic whole milk', 'Dairy', '64 fl oz', 'Carton', 4.49, 0, 'Horizon', False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False)
    (1, 'Silk Original Almond Milk', 'https://target.scene7.com/is/image/Target/GUEST_4f07e8ce-3c2e-4cba-9dee-ad052b7b54b4?wid=1200&hei=1200&qlt=80&fmt=webp', 'Smooth almond milk with a hint of sweetness', 'Dairy', '64 fl oz', 'Carton', 3.49, 0, 'Silk', False, True, True, False, False, False, False, True, True, False, False, False, False, True, True, True, False, False, False, False, False, False),
    (1, 'Land OLakes Salted Butter', 'https://cdn.gardengrocer.com/attachments/photos/high_res/342.jpg?9104', 'Creamy and rich salted butter', 'Dairy', '1 lb', 'Box', 3.99, 10, 'Land OLakes', False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False),
    (1, 'Philadelphia Original Cream Cheese', 'https://target.scene7.com/is/image/Target/GUEST_9b5cddc5-ae46-4618-bfa3-b93b17761c7e?wid=1200&hei=1200&qlt=80&fmt=webp', 'Smooth and creamy classic cream cheese', 'Dairy', '8 oz', 'Tub', 2.49, 0, 'Philadelphia', False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False)
    (1, 'Cool Whip Original Whipped Topping', 'https://target.scene7.com/is/image/Target/GUEST_517ca10c-4115-4a41-82ab-c040c5b57bcf?wid=1200&hei=1200&qlt=80&fmt=webp', 'Light and fluffy whipped topping', 'Dairy', '8 oz', 'Tub', 1.99, 0, 'Cool Whip', False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False),
    (1, 'Reddi-Wip Original Whipped Cream', 'https://target.scene7.com/is/image/Target/GUEST_626ce211-34ca-4218-8975-06ddc1c97d2f?wid=1200&hei=1200&qlt=80&fmt=webp', 'Creamy whipped topping perfect for desserts', 'Dairy', '6.5 oz', 'Can', 2.79, 0, 'Reddi-Wip', False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False),
    (1, 'Chobani Greek Yogurt, Plain', 'https://target.scene7.com/is/image/Target/GUEST_2f19cce5-804f-4bee-bc2c-831d18fb4e98?wid=1200&hei=1200&qlt=80&fmt=webp', 'Thick and creamy plain Greek yogurt', 'Dairy', '32 oz', 'Tub', 5.99, 5, 'Chobani', False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False)


INSERT INTO store_product (product_id, store_id, product_price)
VALUES
    (1, 1, 2.99),
    (1, 2, 1.99), 
    (1, 3, 4.99),
    (2, 1, 1.99), 
    (2, 2, 0.99),
    (2, 3, 1.79),
    (3, 1, 5.99), 
    (3, 2, 2.99),
    (3, 3, 4.79);

INSERT INTO shopper (shopper_firebase_uid, shopper_email, shopper_first_name, shopper_last_name, shopper_profile_pic, shopper_instagram_link, shopper_facebook_link, shopper_dietary_preferences)
VALUES
    ('StSYbI8Gw1c2cm2oV2IDFn4WwAI2', 'tempuser1@example.com', 'Temp', 'User 1', 'profile1.jpg', 'https://www.instagram.com/tempuser1/', 'https://www.facebook.com/tempuser1/', ARRAY['Vegetarian', 'Gluten-Free']),
    ('XtXYbI7Gw1c2cm2oV2IDFn5SsBJ3', 'tempuser2@example.com', 'Temp', 'User 2', 'profile2.jpg', 'https://www.instagram.com/tempuser2/', 'https://www.facebook.com/tempuser2/', ARRAY['Vegan', 'Keto']);

INSERT INTO review (shopper_firebase_uid, store_id, review_rating, review_comment, review_timestamp)
VALUES
    ('StSYbI8Gw1c2cm2oV2IDFn4WwAI2', 1, 4, 'Great store!', '2023-08-23 10:00:00'),
    ('XtXYbI7Gw1c2cm2oV2IDFn5SsBJ3', 2, 2, 'Not a good store.', '2023-08-23 12:30:00'),
    ('StSYbI8Gw1c2cm2oV2IDFn4WwAI2', 3, 5, 'Excellent products.', '2023-08-23 14:45:00'),
    ('XtXYbI7Gw1c2cm2oV2IDFn5SsBJ3', 4, 4, 'Nice place.', '2023-08-23 15:30:00'),
    ('StSYbI8Gw1c2cm2oV2IDFn4WwAI2', 5, 4, 'Loved the selection.', '2023-08-23 18:00:00'),
    ('XtXYbI7Gw1c2cm2oV2IDFn5SsBJ3', 6, 3, 'Average experience.', '2023-08-24 10:15:00'),
    ('StSYbI8Gw1c2cm2oV2IDFn4WwAI2', 7, 4, 'Friendly staff.', '2023-08-24 13:45:00'),
    ('XtXYbI7Gw1c2cm2oV2IDFn5SsBJ3', 8, 1, 'Could be better.', '2023-08-25 09:30:00');